### ISSUE TITLE
Update Established Dates for Companies with Accurate Information

### ISSUE THREAD

**Issue by gaurovgiri** [Know-Nepal/tech-companies#67]
Many company datasets only provide an establishment date accurate up to the year. I have identified a publicly available third-party dataset that contains more precise establishment dates for companies. I would like to contribute to this project by updating the establishment dates with the more accurate information from the third-party dataset.

**Comment by thenishantsapkota** [comment]
I've assigned you this issue. You can work on it

**Comment by TheLearneer** [comment]
Closed in #70
