### ISSUE TITLE
Add Company Regsitration Number in the dataset.

### ISSUE THREAD

**Issue by gaurovgiri** [Know-Nepal/tech-companies#68]
## Is your feature request related to a problem? Please describe.

Given that the dataset pertains to tech companies in Nepal, it is essential to ensure the authenticity of each entry by verifying the company's existence and its official registration status in Nepal.

## Describe the solution you'd like

I suggest to add company registration number as well. So that any company can be verified using [Online Company Registration](https://application.ocr.gov.np/faces/CompanyDetails.jsp).

**Comment by thenishantsapkota** [comment]
Yeah sure! Let's do that @gaurovgiri. I think that will massively help out the information seekers!
