### ISSUE TITLE
More fields for company details

### ISSUE THREAD

**Issue by TheLearneer** [Know-Nepal/tech-companies#9]
## Is your feature request related to a problem?

I think we should add two fields `email` and `phone` for every company to make it easy for users to contact the respective company.

## Describe the solution you'd like

Add the key-value pair for every company in the top level of the company object.

## Describe alternatives you've considered

N/A

## Additional context

Add these missing fields for every company already listed

**Comment by Saphall** [comment]
@TheLearneer Could you help me understand what is the format for `"establishedAt": 1262283300,` date?

**Comment by TheLearneer** [comment]
> @TheLearneer Could you help me understand what is the format for `"establishedAt": 1262283300,` date?

Hi @Saphall Just opened a discussion about it at #11 
Please share a message there if you have any further confusion 😄
